version: 0.2

phases:
  install:
    commands:
      - npm install

  build:
    commands:
      - BPM_PEOPLE_API_URL=$BPM_PEOPLE_API_URL npm run build
      - aws s3 sync dist/ s3://bpm-deploy-people-ui/ --delete
      - echo "S3 Upload Complete"
