export const UserAction = {
  ADD_USERS: 'USER_ADD_USERS',
  ADD_USER: 'USER_ADD_USER',
  CREATION_START: 'USER_CREATION_START',
  CREATION_END: 'USER_CREATION_END',
  EDIT_START: 'USER_EDIT_START',
  EDIT_END: 'EDIT_END',
  EDIT_DATA: 'USER_EDIT_DATA',
  UPDATE: 'USER_UPDATE',
  REMOVE: 'USER_REMOVE',
};

export const MessageAction = {
  MESSAGE: 'INFO_MESSAGE',
};

export const InputErrorAction = {
  ADD: 'ERROR_ADD',
  REMOVE_ALL: 'ERROR_REMOVE_ALL',
};
