export const UserAction = {
  ADD_USERS: 'ADD_USERS',
  ADD_USER: 'ADD_USER',
  USER_CREATION_DATA_RESET: 'USER_CREATION_DATA_RESET',
  USER_CREATION_DATA: 'USER_CREATION_DATA',
  EDIT_USER_ID: 'EDIT_USER_ID',
  EDIT_USER_DATA: 'EDIT_USER_DATA',
  EDIT_USER_FINISH: 'EDIT_USER_FINISH',
  UPDATE_USER: 'UPDATE_USER',
  REMOVE_USER: 'REMOVE_USER',
};

export const MessageAction = {
  MESSAGE: 'MESSAGE',
};

export const InputErrorAction = {
  ADD: 'ADD',
  REMOVE: 'REMOVE',
};
